---
- hosts: all
  become: yes
  remote_user: root
  tasks:
          - name: Instalando o Nginx
            apt:
                    name: nginx
                    state: latest
                    update_cache: yes

          - name: Habilitando o start do Nginx no boot
            service:
                    name: nginx
                    enabled: yes

          - name: Iniciando o Nginx
            service:
                    name: nginx
                    state: started

  handlers:
          - name: Restart o Nginx
            service:
                    name: nginx
                    state: status
