---
- name: "Manage CrowdStrike and Qualys Agents and verify the correct version is installed"
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: true

  vars:
    crowdstrike_rpm: "crowdstrike-agent.rpm"
    qualys_rpm: "qualys-client.rpm"
    update_directory: "roles/agents-fix/files"
    # Define the supported OS and their respective agent versions
    supported_os:
      - name: "CentOS"
        version: "7.9"
        crowdstrike_version: "5.37.0-11111"
        qualys_version: "2.1.0-11111"

      - name: "RedHat"
        version: "8.7"
        crowdstrike_version: "5.37.0-11111"
        qualys_version: "2.1.0-11111"

  tasks:
    - name: "Determine if the OS is supported"
      set_fact:
        os_supported: "{{ item }}"
      with_items: "{{ supported_os }}"
      when: "ansible_facts['distribution'] == item.name and ansible_facts['distribution_version'] == item.version"
      no_log: true

    - name: "Fail if not a supported OS"
      fail:
        msg: "This playbook does not support the current operating system."
      when: os_supported is not defined

    - name: "Check current version of CrowdStrike Falcon Agent"
      shell: "rpm -qa | grep falcon-sensor"
      register: falcon_version
      changed_when: false

    - name: "Check current version of Qualys Cloud Agent"
      shell: "rpm -qa | grep qualys-cloud-agent"
      register: qualys_version
      changed_when: false

    - name: "Copy CrowdStrike Falcon Agent RPM to remote host"
      copy:
        src: "{{ update_directory }}/{{ crowdstrike_rpm }}"
        dest: "/tmp/{{ crowdstrike_rpm }}"
        mode: 0644
      when: >
        falcon_version.stdout != "falcon-sensor-{{ os_supported.crowdstrike_version }}.x86_64"
        and os_supported is defined

    - name: "Copy Qualys Cloud Agent RPM to remote host"
      copy:
        src: "{{ update_directory }}/{{ qualys_rpm }}"
        dest: "/tmp/{{ qualys_rpm }}"
        mode: 0644
      when: >
        qualys_version.stdout != "qualys-cloud-agent-{{ os_supported.qualys_version }}.x86_64"
        and os_supported is defined

    - name: "Install CrowdStrike Falcon Agent"
      yum:
        name: "/tmp/{{ crowdstrike_rpm }}"
        state: present
      when: >
        falcon_version.stdout != "falcon-sensor-{{ os_supported.crowdstrike_version }}.x86_64"
        and os_supported is defined

    - name: "Install Qualys Cloud Agent"
      yum:
        name: "/tmp/{{ qualys_rpm }}"
        state: present
      when: >
        qualys_version.stdout != "qualys-cloud-agent-{{ os_supported.qualys_version }}.x86_64"
        and os_supported is defined

    - name: "Start CrowdStrike Falcon Agent"
      service:
        name: falcon-sensor
        state: started
        enabled: yes
      when: >
        falcon_version.stdout != "falcon-sensor-{{ os_supported.crowdstrike_version }}.x86_64"
        and os_supported is defined

    - name: "Start Qualys Cloud Agent"
      service:
        name: qualys-cloud-agent
        state: started
        enabled: yes
      when: >
        qualys_version.stdout != "qualys-cloud-agent-{{ os_supported.qualys_version }}.x86_64"
        and os_supported is defined