---
- name: "Check and clean /boot directory if usage is above 60%"
  hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - name: "Check the size of the /boot directory"
      shell: "df -h /boot | awk 'NR==2 {print $5}' | sed 's/%//'"
      register: boot_usage

    - name: "Set fact if /boot usage is greater than 60%"
      set_fact:
        boot_usage_high: "{{ boot_usage.stdout | int > 60 }}"

    - name: "Remove unused kernel images if /boot usage is greater than 60%"
      command: >
        rpm -q kernel | sort -V | head -n -2 | xargs sudo yum remove -y
      when: boot_usage_high | bool
      register: cleanup_result
      ignore_errors: yes

    - name: "Check the size of the /boot directory again"
      shell: "df -h /boot | awk 'NR==2 {print $5}' | sed 's/%//'"
      register: boot_usage_after_cleanup
      when: boot_usage_high | bool

    - name: Set fact if /boot usage is still greater than 60% after cleanup
      set_fact:
        boot_usage_still_high: "{{ boot_usage_after_cleanup.stdout | int > 60 }}"
      when: boot_usage_high | bool

    - name: "Fail if /boot usage is still greater than 60%"
      fail:
        msg: "Insufficient space in the /boot directory even after cleanup."
      when: boot_usage_still_high | bool