---
- name: Restrict 'su' usage to wheel group
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Enable pam_wheel.so use_uid in /etc/pam.d/su
      lineinfile:
        path: /etc/pam.d/su
        regexp: '^#?\s*auth\s+required\s+pam_wheel\.so\s+use_uid'
        line: 'auth required pam_wheel.so use_uid'
        state: present