---
- name: "Correlate recently logged-in users with SSH authorized_keys"
  hosts: all
  become: yes
  gather_facts: false

  vars:
    login_days: 90

  tasks:
    ################################################################
    # 1) Find users who have logged in during the last {{ login_days }} days
    ################################################################
    - name: "Check if there are logins in the last {{ login_days }} days"
      shell: "lastlog -t {{ login_days }} | grep -v 'Never' | grep -v 'Username' | awk '{print $1}' | sort -u"
      register: recent_logins
      changed_when: false

    ################################################################
    # 2) For each recently logged-in user, check for SSH keys in authorized_keys
    ################################################################
    - name: "Check authorized_keys for each user that has recently logged in"
      shell: "grep -E 'ssh-(rsa|ecdsa|ed25519)' /home/{{ item }}/.ssh/authorized_keys 2>/dev/null || true"
      loop: "{{ recent_logins.stdout_lines }}"
      register: key_check
      changed_when: false

    ################################################################
    # 3) Correlate results (find users with non-empty grep results)
    ################################################################
    - name: "Collect correlated users who have SSH keys"
      set_fact:
        correlated_users: "{{ key_check.results | selectattr('stdout','!=','') | map(attribute='item') | list }}"

    ################################################################
    # 4) Display which users match both conditions
    ################################################################
    - name: "Debug correlated users"
      debug:
        msg: >
          Users who logged in within the last {{ login_days }} days AND have SSH keys:
          {{ correlated_users if correlated_users|length > 0 else "None found." }}